services:
  - type: web
    name: campusmart-api
    env: node
    rootDir: .
    buildCommand: npm install && npm run build --workspace=packages/shared-types && npm run build --workspace=packages/validation && npx prisma generate --schema=apps/api/prisma/schema.prisma && npx prisma migrate deploy --schema=apps/api/prisma/schema.prisma && npm run build --workspace=apps/api
    startCommand: npm run start --workspace=apps/api
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
